#!/bin/bash

chmod 755 oohub_start
echo "Hello OOHub!"
echo -e "   ____   ____  _    _       _     
  / __ \ / __ \| |  | |     | |    
 | |  | | |  | | |__| |_   _| |__  
 | |  | | |  | |  __  | | | | '_ \ 
 | |__| | |__| | |  | | |_| | |_) |
  \____/ \____/|_|  |_|\__,_|_.__/ 
                                   
                                   "


docker-compose down -v
rm -rf ./jupyterhub/jupyterhub_cookie_secret
docker-compose up --build

exit 0
