#!/bin/bash

chmod 755 oohub_start
echo "Hello OOHub!"
echo -e " ██████╗  ██████╗ ██╗  ██╗██╗   ██╗██████╗ 
██╔═══██╗██╔═══██╗██║  ██║██║   ██║██╔══██╗
██║   ██║██║   ██║███████║██║   ██║██████╔╝
██║   ██║██║   ██║██╔══██║██║   ██║██╔══██╗
╚██████╔╝╚██████╔╝██║  ██║╚██████╔╝██████╔╝
 ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ 
                                           "


docker-compose down -v
rm -rf ./jupyterhub/jupyterhub_cookie_secret
docker-compose up --build

exit 0
